function res=plotcpufev(ndelmax,cputot,fevtot,tdeltot)
% plot log10 of cpu time for 5 methods divided by the cpu time for fEc 
cputot6=cputot(:,2);
fevtot6=fevtot(:,2);
% scaling by data for constant time step
for j=1:ndelmax
   for k=1:6
      cputot2(j,k)=cputot(j,k)/cputot6(j);
      fevtot2(j,k)=fevtot(j,k)/fevtot6(j);
   end
end
%subplot(2,1,1)
% Fig 4
plot(tdeltot(1:ndelmax),log10(cputot2(1:ndelmax,1)),'g*', ...
    tdeltot(1:ndelmax),log10(cputot2(1:ndelmax,2)),'k-.',tdeltot(1:ndelmax),log10(cputot2(1:ndelmax,3)),'bo', ...
     tdeltot(1:ndelmax),log10(cputot2(1:ndelmax,4)),'m^',tdeltot(1:ndelmax),log10(cputot2(1:ndelmax,5)),'c+', ...
     tdeltot(1:ndelmax),log10(cputot2(1:ndelmax,6)),'rx')
% plot(tdeltot(1:ndelmax),cputot2(1:ndelmax,1),'g*', ...
%     tdeltot(1:ndelmax),cputot2(1:ndelmax,2),'k-.',tdeltot(1:ndelmax),cputot2(1:ndelmax,3),'bo', ...
%      tdeltot(1:ndelmax),cputot2(1:ndelmax,4),'m^',tdeltot(1:ndelmax),cputot2(1:ndelmax,5),'c+', ...
%      tdeltot(1:ndelmax),cputot2(1:ndelmax,6),'rx')
%subplot(2,1,2)
%plot(tdeltot(1:ndelmax),log10(fevtot2(1:ndelmax,1)),'g*',tdeltot(1:ndelmax),log10(fevtot2(1:ndelmax,2)),'k-.', ...
%    tdeltot(1:ndelmax),log10(fevtot2(1:ndelmax,3)),'bo', ...
%	tdeltot(1:ndelmax),log10(fevtot2(1:ndelmax,4)),'m^',tdeltot(1:ndelmax),log10(fevtot2(1:ndelmax,5)),'c+', ...
%    tdeltot(1:ndelmax),log10(fevtot2(1:ndelmax,6)),'rx')
res=0;

